extends Node
## Music, ambience and sound effects (autoload "Sound").
## All audio lives in res://assets/audio and is generated by
## tools/audio_gen/synth.py. To use your own music, drop OGG files with the
## same names (music_day / music_golden / music_night / music_title).

const DIR := "res://assets/audio/"
const MUSIC_DB := -9.0
const VOWELS := "aeiou"

var _streams := {}
var _music: Array[AudioStreamPlayer] = []
var _music_idx := 0
var _music_track := ""
var _music_override := ""
var _pool: Array[AudioStreamPlayer] = []
var _pool_i := 0
var _ocean: AudioStreamPlayer
var _night: AudioStreamPlayer
var _bird_timer := 3.0
var muted_music := false


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	for bus in ["Music", "SFX", "Ambience"]:
		if AudioServer.get_bus_index(bus) == -1:
			AudioServer.add_bus()
			var i := AudioServer.bus_count - 1
			AudioServer.set_bus_name(i, bus)
			AudioServer.set_bus_send(i, "Master")
	# A touch of room on effects keeps them soft.
	var sfx := AudioServer.get_bus_index("SFX")
	var rv := AudioEffectReverb.new()
	rv.room_size = 0.3
	rv.wet = 0.12
	rv.dry = 1.0
	AudioServer.add_bus_effect(sfx, rv)
	for i in 2:
		var p := AudioStreamPlayer.new()
		p.bus = "Music"
		p.volume_db = -80.0
		add_child(p)
		_music.append(p)
	for i in 12:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_pool.append(p)
	_ocean = _loop_player("amb_ocean", "Ambience", -80.0)
	_night = _loop_player("amb_night", "Ambience", -80.0)


func stream(sound_name: String) -> AudioStream:
	if _streams.has(sound_name):
		return _streams[sound_name]
	var s: AudioStream = null
	for ext in [".ogg", ".wav"]:
		if ResourceLoader.exists(DIR + sound_name + ext):
			s = load(DIR + sound_name + ext)
			break
	_streams[sound_name] = s
	return s


func _loop_player(sound_name: String, bus: String, db: float) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = bus
	p.volume_db = db
	var s := stream(sound_name)
	if s is AudioStreamOggVorbis:
		s.loop = true
	p.stream = s
	add_child(p)
	if s:
		p.play()
	return p


## A looping positional sound (fountain, engine…).
func loop_3d(sound_name: String, parent: Node3D, unit_size: float = 4.0, db: float = 0.0) -> AudioStreamPlayer3D:
	var p := AudioStreamPlayer3D.new()
	var s := stream(sound_name)
	if s is AudioStreamOggVorbis:
		s.loop = true
	elif s is AudioStreamWAV:
		var w := s as AudioStreamWAV
		w.loop_mode = AudioStreamWAV.LOOP_FORWARD
		w.loop_begin = 0
		w.loop_end = int(w.get_length() * w.mix_rate)
	p.stream = s
	p.bus = "Ambience"
	p.unit_size = unit_size
	p.volume_db = db
	p.max_distance = unit_size * 12.0
	parent.add_child(p)
	if s:
		p.play()
	return p


func play(sound_name: String, db: float = 0.0, pitch: float = 1.0) -> void:
	var s := stream(sound_name)
	if s == null:
		return
	var p := _pool[_pool_i]
	_pool_i = (_pool_i + 1) % _pool.size()
	p.stream = s
	p.volume_db = db
	p.pitch_scale = pitch
	p.play()


func play_ui(sound_name: String) -> void:
	if stream("ui_" + sound_name):
		play("ui_" + sound_name, -6.0)
	else:
		play(sound_name, -6.0)


## Animalese-style babble: one vowel blip per letter, pitched by the speaker's voice.
func babble(ch: String, voice: float = 1.0) -> void:
	var c := ch.to_lower()
	var v := c if VOWELS.contains(c) else VOWELS[c.unicode_at(0) % 5] if c.length() > 0 else "a"
	var pitch := voice * (1.0 + float(c.unicode_at(0) % 7) * 0.025) * randf_range(0.97, 1.03)
	play("babble_" + v, -11.0, pitch)


func footstep(surface: String, db: float = -14.0) -> void:
	play("step_%s_%d" % [surface, randi() % 3], db + randf_range(-1.5, 1.5), randf_range(0.92, 1.08))


## What's underfoot at a world position.
func surface_at(pos: Vector3) -> String:
	var t = Game.terrain
	if t == null:
		return "grass"
	var h: float = t.height_at(pos.x, pos.z)
	if pos.y - h > 0.35:
		return "wood"
	var sp: Color = t.splat_at(pos.x, pos.z)
	if sp.g > 0.5 or sp.b > 0.5:
		return "stone"
	if h < 1.45:
		return "sand"
	return "grass"


# ---------------------------------------------------------------------------
# Music
# ---------------------------------------------------------------------------

func music(track: String, fade: float = 2.5) -> void:
	if track == _music_track:
		return
	_music_track = track
	var s := stream("music_" + track)
	if s is AudioStreamOggVorbis:
		s.loop = true
	var old := _music[_music_idx]
	_music_idx = 1 - _music_idx
	var new := _music[_music_idx]
	new.stream = s
	new.volume_db = -60.0
	if s:
		new.play()
	var tw := create_tween().set_parallel(true)
	tw.tween_property(old, "volume_db", -60.0, fade)
	tw.tween_property(new, "volume_db", -80.0 if muted_music else MUSIC_DB, fade)
	tw.chain().tween_callback(old.stop)


## Forces a track (e.g. the title screen) until cleared with "".
func override_music(track: String) -> void:
	_music_override = track
	if track != "":
		music(track, 1.0)


func toggle_music() -> bool:
	muted_music = not muted_music
	_music[_music_idx].volume_db = -80.0 if muted_music else MUSIC_DB
	return muted_music


func _process(delta: float) -> void:
	var preset := "day"
	if Game.atmosphere:
		preset = Game.atmosphere.current
	if _music_override == "":
		music(preset)
	# Ocean: louder near the coast and on the beach.
	var p: Node3D = Game.player
	if p and Game.terrain:
		var sd := WorldLayout.island_sd(p.global_position.x, p.global_position.z)
		var near := clampf(1.0 - (-sd - 4.0) / 30.0, 0.0, 1.0)
		var target := lerpf(-34.0, -10.0, near)
		_ocean.volume_db = lerpf(_ocean.volume_db, target, clampf(delta * 1.5, 0.0, 1.0))
	elif _ocean.volume_db < -30.0:
		_ocean.volume_db = -22.0
	var night_target := -14.0 if preset == "night" else -80.0
	_night.volume_db = move_toward(_night.volume_db, night_target, delta * 12.0)
	# Birdsong during the day.
	if preset != "night":
		_bird_timer -= delta
		if _bird_timer <= 0.0:
			_bird_timer = randf_range(2.5, 7.0)
			play("bird_%d" % (randi() % 4), randf_range(-24.0, -17.0), randf_range(0.9, 1.15))


func _unhandled_input(event: InputEvent) -> void:
	if event.is_action_pressed("music"):
		var m := toggle_music()
		if Game.hud:
			Game.hud.toast("♪ Music off" if m else "♪ Music on")
